### ISSUE TITLE
Problem with JS not working on Heroku

### ISSUE THREAD

**Issue by Talha5** [mwlang/gentelella-rails#9]
When including `gem 'gentelella-rails'`. JS works fine on local but stops working on Heroku. i followed all the instructions. Using rails 5.1.2. Works fine if i remove `gentelella-custom.js` file.

**Comment by Miccighel** [comment]
I have the same problem, i opened an issue because on Heroku i cannot explore the files.

**Comment by Talha5** [comment]
Your rails version? I got it working fine on `rails 5.0.1` but crashes on `5.1.2`

**Comment by mwlang** [comment]
Hmmm...this may be a 5.1 issue.  It may be that some of the gems utilized are not 5.1 ready or it may be that this gem's not 5.1 ready.  I'll try to find some time to dig in and see.

In any event, I need to update the README to clarify the role of gentelella-custom.js -- this really is just where you'd load anything else you need for your specific project, but it ships (perhaps erroneously) with an example of what gentelella-custom can be...which is all the JS specific to making your own project work.  In this case, it was the custom JS supplied by the Gentelella theme itself.

**Comment by Miccighel** [comment]
@Talha5 5.1!

I'll keep in touch to this issue to get any news about it, if you can fix that it will be awesome. Thanks.

**Comment by mwlang** [comment]
@Miccighel and @Talha5 I set up a demo project that loads Rails 5.0.1 and Rails 5.1.2 and both work locally.  Can either of you try deploying the demo to Heroku after confirming it works locally for you?  

The demo with 5.1 and 5.2 working examples: https://github.com/mwlang/gentelella-rails-demo

**Comment by b-mandelbrot** [comment]
I´m using Rails 5.1 and Ruby 2.3.3. I had to use the following setting for the precompile to work:

`Rails.application.config.assets.precompile += %w( *.js *.css )`

But now,  I'm having another kind of error:

`I, [2017-07-21T03:12:29.041916 #6274]  INFO -- : Writing /Users/bruno/Projects/indeva/public/assets/date/da-DK-6c551b4dc9297b663c23dc2337fed6edbd7caea67b3869843e4fefa8dd93aeb3.js.gz
rake aborted!
Encoding::InvalidByteSequenceError: "\xE7" followed by "a" on UTF-8`

Thanks!

**Comment by Talha5** [comment]
@mwlang I was also successfully running it over localhost by adding `Rails.application.config.assets.paths << Rails.root.join('node_modules')` but it js wasnt working when deployed to heroku.

**Comment by mwlang** [comment]
@b-mandelbrot: That data/da-DK.js failing on invalid byte sequence seems to be a clue that there's a problem encoding and compressing the JS with.  However, I'm able to follow your steps and precompile everything on the demo rails project.  Can you try to reproduce this with the demo? 

@Talha5 node_modules could contain anything.  Are you geting the same error writing da-DK-[fingerprint].js.gz?  That is, the Encoding::InvalidByteSequenceError that @b-mandelbrot reports?

**Comment by b-mandelbrot** [comment]
@mwlang I've tested with rails 5.1.x demo application, but it also doesn't work in production (local/heroku) and when adding the line (config.assets.precompile) I have the same encoding error.  I think there is a problem with datejs-rails see: (https://github.com/datejs-utf8/datejs-rails).

**Comment by mwlang** [comment]
@b-mandelbrot I'm able to reproduce now locally.  It's the DateJS library that's included via the datejs-rails gem.  Trying to see if I can resolve the issue.

**Comment by mwlang** [comment]
turned out there were a total of three separate issues to resolve along the way.  

1st: moment.js is required for fullcalendar.  This has been added to the gem's asset pipeline.  Why it didn't cause issues in development mode is a mystery!

2nd: It wasn't enough to add just "gentelella.js" to the gem's precompile list to fully build out the asset pipeline.  This was prompting everyone to add *.js and *.css to their project's precompile list.

3rd: datejs-rails is dormant, and has encoding issues that are unresolved since 2014, so I switched to bower to get latest sources.

To fix your project:
~~~
bundle update gentelella-rails
~~~ 
To get to the latest release of the gem.  0.1.8 at the time of this note.

REMOVE Rails.application.config.assets.precompile += %w( *.js *.css ) from your Rails project.  If this line is left in, you'll start see a whole new set of issues when it gets to bootstrap-sass gem.  The long/short of it: adding that line to the gem pulled in exactly the right *.js and *.css that the gem depends on to work.  Adding it to the Rails project pulls in every *.js and *.css of every gem in the Rails app and this gets messy quick!

Here's a working Heroku deploy:  https://stormy-shore-66376.herokuapp.com/index.html
This is just the (Rails 5.1.x example](https://github.com/mwlang/gentelella-rails-demo/tree/master/examples/rails.5.1.x) tweaked to use 'pg' gem.  I will likely delete the Heroku dyno in a couple weeks, so check it out while you can.

**Comment by b-mandelbrot** [comment]
@mwlang Perfect! I tested on my project and everything is working fine, including Heroku. Thank you very much!
